// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Car: typeof import('./components/simulation/Car.vue')['default']
    CarbonCircleSolid: typeof import('~icons/carbon/circle-solid')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    CarEntity: typeof import('./components/simulation/CarEntity.vue')['default']
    CarForm: typeof import('./components/forms/CarForm.vue')['default']
    Date: typeof import('./components/Date.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    NewCar: typeof import('./components/forms/NewCar.vue')['default']
    NewTrafficLight: typeof import('./components/forms/NewTrafficLight.vue')['default']
    Road: typeof import('./components/simulation/Road.vue')['default']
    Simulation: typeof import('./components/simulation/Simulation.vue')['default']
    Spacer: typeof import('./components/Spacer.vue')['default']
    TrafficLight: typeof import('./components/simulation/TrafficLight.vue')['default']
    TrafficLightEntity: typeof import('./components/simulation/TrafficLightEntity.vue')['default']
    TrafficLightForm: typeof import('./components/forms/TrafficLightForm.vue')['default']
  }
}

export { }
