// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonUndo: typeof import('~icons/carbon/undo')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Date: typeof import('./components/Date.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Spacer: typeof import('./components/Spacer.vue')['default']
  }
}

export { }
